### PR TITLE
1st build 

### PR DESCRIPTION
**Pull request by BalajiSriraman**
to be explained in gmeet

### CODE REVIEW

**Comment by anilgulecha** [comment]
Feedback: on this PR

1) commit messages should be well written -- not "new".

This is great resource: https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

**Comment by anilgulecha** [comment]
Feedback: on this PR

1) commit messages should be well written -- not "new".
You can refer to this blog for example https://initialcommit.com/blog/git-commit-messages-best-practices

**Comment by anilgulecha** [comment]
Otherwise, a good start. keep it up.

**Review by PatelNeelMahesh — APPROVED** [review]
Add and maintain README file as you add more features.

**Comment by anilgulecha** [comment]
BTW, commit should me merged by students themselves. Once they've acted on the feedback. Mentors can focus only on code reviews/feedback

**Pull request merged**
